-- verify-launch.sql
-- Pre-launch DB readiness check for the My Yoga Classes site.
-- Paste into the Supabase SQL editor (or: psql "$SUPABASE_DB_URL" -f verify-launch.sql).
-- Every row should read PASS. Any FAIL means that migration's object is not applied to the live DB
-- (a "feature looks broken but is actually unwired" trap). Read-only; safe to run on production.
-- Generated from supabase/migrations/0001..0029, audited against the files, then hand-patched after review:
--   * idempotency / partial-unique indexes are checked, not just their columns;
--   * admin_kpis verifies the 0022 per-currency REBUILD via a body match, not just the name (it predates 0022 in 0006);
--   * the five app-critical function checks assert argument count (pronargs), not just the name;
--   * the pack-credits data check uses jsonb extraction so a missing column reports FAIL instead of ABORTING the script.
-- No statement can raise: catalog probes use to_regclass()/catalog joins (NULL on miss), and the one data probe
-- never names a maybe-missing column (it reads values out of to_jsonb(row), so an absent column yields FAIL, not an error).
-- Run as the Supabase SQL editor / service (postgres) role: it reads pg_get_functiondef, storage.buckets and pg_policies,
-- which are role-visibility sensitive — running as a low-privilege role (e.g. authenticated) could under-report.

SELECT
  CASE WHEN ok THEN '✅ PASS' ELSE '❌ FAIL' END AS status,
  severity,
  check_name,
  CASE WHEN ok THEN '' ELSE fix END AS fix_if_failed
FROM (
  SELECT 'book_session RPC public.book_session(uuid,uuid,timestamptz,timestamptz,boolean) (0017 booking integrity)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='book_session' AND p.pronargs=5)) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0017_booking_integrity.sql'::text AS fix
  UNION ALL SELECT 'credit_ledger table (0011 Razorpay billing)'::text AS check_name, (to_regclass('public.credit_ledger') IS NOT NULL) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0011_razorpay_billing.sql'::text AS fix
  UNION ALL SELECT 'credit-grant RPC public.grant_session_credits (0011 Razorpay billing)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='grant_session_credits')) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0011_razorpay_billing.sql'::text AS fix
  UNION ALL SELECT 'customer_credits table (0011 Razorpay billing)'::text AS check_name, (to_regclass('public.customer_credits') IS NOT NULL) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0011_razorpay_billing.sql'::text AS fix
  UNION ALL SELECT 'medical_document_access_log table (0027 medical documents)'::text AS check_name, (to_regclass('public.medical_document_access_log') IS NOT NULL) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'medical_document_shares table (0027 medical documents)'::text AS check_name, (to_regclass('public.medical_document_shares') IS NOT NULL) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'medical_documents table (0027 medical documents)'::text AS check_name, (to_regclass('public.medical_documents') IS NOT NULL) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'medical-documents PRIVATE storage bucket (0027 medical documents)'::text AS check_name, (EXISTS (SELECT 1 FROM storage.buckets WHERE id='medical-documents' AND public=false)) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'payments.amount_cents column (renamed from amount_aud_cents) (0022 multi-currency)'::text AS check_name, (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='payments' AND column_name='amount_cents')) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0022_multi_currency.sql'::text AS fix
  UNION ALL SELECT 'payments.razorpay_payment_id column + UNIQUE idempotency index (0011 Razorpay billing)'::text AS check_name, (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='payments' AND column_name='razorpay_payment_id') AND to_regclass('public.payments_razorpay_payment_id_key') IS NOT NULL) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0011_razorpay_billing.sql'::text AS fix
  UNION ALL SELECT 'plan_prices multi-currency child table (0022 multi-currency)'::text AS check_name, (to_regclass('public.plan_prices') IS NOT NULL) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0022_multi_currency.sql'::text AS fix
  UNION ALL SELECT 'plans.price_base_cents column (renamed from price_aud_cents) (0022 multi-currency)'::text AS check_name, (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='plans' AND column_name='price_base_cents')) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0022_multi_currency.sql'::text AS fix
  UNION ALL SELECT 'profiles_lock_sensitive trigger fires on INSERT OR UPDATE (0029 service-path fix — proxy only)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_trigger tg JOIN pg_class r ON r.oid=tg.tgrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE tg.tgname='profiles_lock_sensitive' AND r.relname='profiles' AND n.nspname='public' AND (tg.tgtype & 4)=4 AND (tg.tgtype & 16)=16)) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0029_profiles_role_service_path_fix.sql'::text AS fix
  UNION ALL SELECT 'promote_to_teacher RPC public.promote_to_teacher(uuid,uuid,uuid) (0025 teacher provisioning)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='promote_to_teacher' AND p.pronargs=3)) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0025_teacher_provisioning.sql'::text AS fix
  UNION ALL SELECT 'share_medical_document RPC (0027 medical documents)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='share_medical_document')) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'teacher_has_document_share RPC (0027 medical documents)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_has_document_share')) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'user_role enum has ''teacher'' value (0024_teacher_role) — absence KILLS teacher login'::text AS check_name, (EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND t.typname='user_role' AND e.enumlabel='teacher')) AS ok, 'blocker'::text AS severity, 'psql -f supabase/migrations/0024_teacher_role.sql'::text AS fix
  UNION ALL SELECT 'admin demote RPC public.demote_from_admin(uuid) (0010 admin demote)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='demote_from_admin' AND p.pronargs=1)) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0010_admin_demote.sql'::text AS fix
  UNION ALL SELECT 'admin-write RLS policy bookings_self_update_cancel — representative of 0018 RLS/grants hardening'::text AS check_name, (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='bookings' AND policyname='bookings_self_update_cancel')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0018_rls_and_grants_hardening.sql'::text AS fix
  UNION ALL SELECT 'billing_interval enum has ''one_time'' (0020 credit packs)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND t.typname='billing_interval' AND e.enumlabel='one_time')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0020_credit_packs.sql'::text AS fix
  UNION ALL SELECT 'customer_booked_teacher RPC (0027 medical documents)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='customer_booked_teacher')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'demote_from_teacher RPC public.demote_from_teacher(uuid) (0025/0026 teacher provisioning)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='demote_from_teacher' AND p.pronargs=1)) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0025_teacher_provisioning.sql'::text AS fix
  UNION ALL SELECT 'discount_type enum has ''fixed_amount_cents'' value (0022 multi-currency)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND t.typname='discount_type' AND e.enumlabel='fixed_amount_cents')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0022_multi_currency.sql'::text AS fix
  UNION ALL SELECT 'owns_medical_document RPC (0027 medical documents)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='owns_medical_document')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'pack-5 / pack-10 credit packs seeded with session_credits>0 (0020 credit packs)'::text AS check_name, (EXISTS (SELECT 1 FROM public.plans p WHERE (to_jsonb(p.*)->>'slug')='pack-5' AND (to_jsonb(p.*)->>'session_credits')::numeric>0) AND EXISTS (SELECT 1 FROM public.plans p WHERE (to_jsonb(p.*)->>'slug')='pack-10' AND (to_jsonb(p.*)->>'session_credits')::numeric>0)) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0020_credit_packs.sql'::text AS fix
  UNION ALL SELECT 'per-booking refund-once index credit_ledger_booking_refund_once (0021 refund idempotency)'::text AS check_name, (to_regclass('public.credit_ledger_booking_refund_once') IS NOT NULL) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0021_refund_idempotency_and_blocklist.sql'::text AS fix
  UNION ALL SELECT 'refund clawback RPC public.clawback_session_credits + credit_ledger.external_ref (0019 refund reconciliation)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='clawback_session_credits') AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='credit_ledger' AND column_name='external_ref')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0019_refund_reconciliation.sql'::text AS fix
  UNION ALL SELECT 'refund-once RPC public.refund_session_credit(uuid,uuid) (0021 refund idempotency + blocklist)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='refund_session_credit' AND p.pronargs=2)) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0021_refund_idempotency_and_blocklist.sql'::text AS fix
  UNION ALL SELECT 'revoke_medical_document_share RPC (0027 medical documents)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='revoke_medical_document_share')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0027_medical_documents.sql'::text AS fix
  UNION ALL SELECT 'sessions overlap EXCLUDE constraint sessions_no_overlap (0017 booking integrity)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_constraint c JOIN pg_class r ON r.oid=c.conrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE c.conname='sessions_no_overlap' AND r.relname='sessions' AND n.nspname='public')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0017_booking_integrity.sql'::text AS fix
  UNION ALL SELECT 'teachers_profile_id_uniq partial unique index (0028 teacher link integrity)'::text AS check_name, (to_regclass('public.teachers_profile_id_uniq') IS NOT NULL) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0028_teacher_link_integrity.sql'::text AS fix
  UNION ALL SELECT 'teachers.profile_id column (exists since 0002; used by 0025 teacher link)'::text AS check_name, (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='teachers' AND column_name='profile_id')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0002_teachers.sql'::text AS fix
  UNION ALL SELECT 'trigger teachers_revoke_shares_on_unlink on public.teachers (0028 teacher link integrity / PHI)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_trigger tg JOIN pg_class r ON r.oid=tg.tgrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE tg.tgname='teachers_revoke_shares_on_unlink' AND r.relname='teachers' AND n.nspname='public')) AS ok, 'high'::text AS severity, 'psql -f supabase/migrations/0028_teacher_link_integrity.sql'::text AS fix
  UNION ALL SELECT 'admin_kpis() rebuilt for per-currency revenue (0022 multi-currency)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='admin_kpis' AND pg_get_functiondef(p.oid) ILIKE '%revenue_mtd_by_currency%')) AS ok, 'medium'::text AS severity, 'psql -f supabase/migrations/0022_multi_currency.sql'::text AS fix
  UNION ALL SELECT 'bookings.reminded_at_24h / reminded_at_1h columns (0016 reminder idempotency)'::text AS check_name, (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='bookings' AND column_name='reminded_at_24h') AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='bookings' AND column_name='reminded_at_1h')) AS ok, 'medium'::text AS severity, 'psql -f supabase/migrations/0016_booking_reminder_idempotency.sql'::text AS fix
  UNION ALL SELECT 'class_categories.helps_with content column (0023 goal-based categories)'::text AS check_name, (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='class_categories' AND column_name='helps_with')) AS ok, 'medium'::text AS severity, 'psql -f supabase/migrations/0023_goal_based_categories.sql'::text AS fix
  UNION ALL SELECT 'class_categories.what_to_expect content column (0023 goal-based categories)'::text AS check_name, (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='class_categories' AND column_name='what_to_expect')) AS ok, 'medium'::text AS severity, 'psql -f supabase/migrations/0023_goal_based_categories.sql'::text AS fix
  UNION ALL SELECT 'newsletter subscribe RPC public.subscribe_newsletter(text,text) (0007 security fixes)'::text AS check_name, (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='subscribe_newsletter')) AS ok, 'medium'::text AS severity, 'psql -f supabase/migrations/0007_security_fixes.sql'::text AS fix
  UNION ALL SELECT 'storage bucket ''promotional-media'' (0008 storage buckets)'::text AS check_name, (EXISTS (SELECT 1 FROM storage.buckets WHERE id='promotional-media')) AS ok, 'medium'::text AS severity, 'psql -f supabase/migrations/0008_storage_buckets.sql'::text AS fix
  UNION ALL SELECT 'storage bucket ''teacher-media'' (0008 storage buckets)'::text AS check_name, (EXISTS (SELECT 1 FROM storage.buckets WHERE id='teacher-media')) AS ok, 'medium'::text AS severity, 'psql -f supabase/migrations/0008_storage_buckets.sql'::text AS fix
) s
ORDER BY ok ASC,
         array_position(ARRAY['blocker','high','medium','low'], severity),
         check_name;
